#ifndef CONFIG_H
#define CONFIG_H

#define DEBUG
#define DEBUG_STR


#ifdef DEBUG_STR
#define PRINT(message) Serial.println("Debug: "+((String)message))
#else
#define PRINT(message) 0
#endif

///GAME
#define PIN_RIGHT_BUTTON 36
#define PIN_LEFT_BUTTON 34
#define BUTTON_SIZE 2

#define PIN_SENSOR_SHARP A0
#define THRESHOLD_GLASS_PRESENT 270

#define DIVIDE_SPEED 0.4
#define GAME_DELAY_CHECK 10
#define GAME_POSITION_CENTER 2
#define GAME_POSITION_CENTER1 3

#define GAME_RESET_SPEED 100


///ELECTROVANNE
#define OPEN LOW
#define CLOSE HIGH
#define PIN_ELECTROVALVE_0 53
#define PIN_ELECTROVALVE_1 41
#define PIN_ELECTROVALVE_2 43
#define PIN_ELECTROVALVE_3 45
#define PIN_ELECTROVALVE_4 47
#define PIN_ELECTROVALVE_5 49
#define TIME_ELECTROVALVE_OPEN_MS 100

#define ELECTROVALVE_SIZE 6

///CHARRIOT
#define PIN_2_MOTOR 11 //IN3
#define PIN_1_MOTOR 12 //IN4
#define PIN_EN_MOTOR 13



#define MOTOR_SPEED_MAX_TIME_MS 50
#define MOTOR_MAX_VALUE 240
#define MOTOR_MIN_VALUE 190

//#define MOTOR_SLICE_VALUE  (((MOTOR_MAX_VALUE - MOTOR_MIN_VALUE)*GAME_DELAY_CHECK)/MOTOR_SPEED_MAX_TIME_MS)
#define MOTOR_SLICE_VALUE  10

//#define MOTOR_MOVE_POSITION_MULTIPLE ((MOTOR_MAX_VALUE/MOTOR_SLICE_VALUE))
#define MOTOR_MOVE_POSITION_MULTIPLE 10

//#define MOTOR_CENTER_SPEED_VALUE ((MOTOR_SLICE_VALUE*MOTOR_MOVE_POSITION_MULTIPLE)) /// must be higher than a step 
#define MOTOR_CENTER_SPEED_VALUE 160 /// must be higher than a step 

#define PIN_SERVO 10
#define SERVO_ANGLE_MIN 20
#define SERVO_ANGLE_MAX 58
#define SERVO_DELAY_MS 7



#define PIN_SENSOR_POSITION_0 50
#define PIN_SENSOR_POSITION_1 48
#define PIN_SENSOR_POSITION_2 46
#define PIN_SENSOR_POSITION_3 44
#define PIN_SENSOR_POSITION_4 42
#define PIN_SENSOR_POSITION_5 40

#define PIN_SENSOR_POSITION_FDCG 38
#define PIN_SENSOR_POSITION_FDCD 52
#define SENSOR_FDC_SIZE 2
#define SENSOR_POSITION_SIZE 6

// #define DELAY_CHECK_MOVE_POSITION 200


#define POUR_TIME_MS 5000 
///COMMUNICATION
#define BAUDRATES 9600
#define BUFFERSIZE 255
#define TIMEOUT_SERIAL 100
#define END_COMMAND_CHAR '}'

///CUVE
#define PIN_TANK_SENSOR 39
#define PIN_TANK_PUMP 51
#endif
