#ifndef CONFIG_H
#define CONFIG_H

#define DEBUG

#ifdef DEBUG
#define PRINT(message) Serial.println("Debug: "+((String)message))
#else
#define PRINT(message) 0
#endif

///GAME
#define PIN_RIGHT_BUTTON 12
#define PIN_LEFT_BUTTON 11
#define BUTTON_SIZE 2

#define PIN_MAIN_PUMP 39
#define PIN_SENSOR_SHARP A1
#define THRESHOLD_GLASS_PRESENT 800
#define GAME_DELAY_CHECK 20
#define GAME_POSITION_CENTER 0


///ELECTROVANNE
#define OPEN HIGH
#define CLOSE LOW
#define PIN_ELECTROVALVE_0 53
#define PIN_ELECTROVALVE_1 51
#define PIN_ELECTROVALVE_2 49
#define PIN_ELECTROVALVE_3 47
#define PIN_ELECTROVALVE_4 45
#define PIN_ELECTROVALVE_5 43

#define ELECTROVALVE_SIZE 6

///CHARRIOT
#define PIN_1_MOTOR 7 //IN4
#define PIN_2_MOTOR 6 //IN3
#define PIN_EN_MOTOR 5



#define MOTOR_SPEED_MAX_TIME_MS 100
#define MOTOR_MAX_VALUE 200
#define MOTOR_MIN_VALUE 0 
#define MOTOR_SLICE_VALUE  (((MOTOR_MAX_VALUE - MOTOR_MIN_VALUE)*GAME_DELAY_CHECK)/MOTOR_SPEED_MAX_TIME_MS)

#define MOTOR_MOVE_POSITION_MULTIPLE ((MOTOR_MAX_VALUE/MOTOR_SLICE_VALUE))
#define MOTOR_CENTER_SPEED_VALUE ((MOTOR_SLICE_VALUE*2)) /// must be higher than a step 

//#define MOTOR_SLICE_VALUE  20
//#define MOTOR_CENTER_SPEED_VALUE 80 /// must be higher than a step 
//#define MOTOR_MOVE_POSITION_MULTIPLE 5

#define PIN_SERVO 3
#define SERVO_ANGLE_MIN 20
#define SERVO_ANGLE_MAX 58
#define SERVO_DELAY_MS 8

#define PIN_SENSOR_POSITION_0 22
#define PIN_SENSOR_POSITION_1 23
#define PIN_SENSOR_POSITION_2 24
#define PIN_SENSOR_POSITION_3 25
#define PIN_SENSOR_POSITION_4 26
#define PIN_SENSOR_POSITION_5 27
#define SENSOR_POSITION_SIZE 6

// #define DELAY_CHECK_MOVE_POSITION 200


#define POUR_TIME_MS 5000 
///COMMUNICATION
#define BAUDRATES 9600
#define BUFFERSIZE 255
#define TIMEOUT_SERIAL 100
#define END_COMMAND_CHAR '}'

///CUVE
#define PIN_TANK_SENSOR A0
#define PIN_TANK_PUMP 41
#define THRESHOLD_TANK_FULL 100
#endif